# Generated by Django 4.0.4 on 2022-05-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('company', models.CharField(max_length=32)),
                ('street_address', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=32)),
                ('state_province_region', models.CharField(max_length=32)),
                ('postal_code', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
                ('ship_code', models.CharField(max_length=20)),
                ('tracking_number', models.CharField(max_length=20)),
            ],
        ),
    ]
