# Generated by Django 4.0.4 on 2022-05-15 21:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_shipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemForShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.item')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.shipment')),
            ],
        ),
    ]
