# Generated by Django 4.0.4 on 2022-05-16 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0004_location_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.location'),
        ),
    ]
