# Generated by Django 4.0.4 on 2022-05-16 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0005_alter_weather_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='id',
        ),
        migrations.AlterField(
            model_name='weather',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory_app.location'),
        ),
    ]
