# Generated by Django 4.0.4 on 2022-05-16 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0006_remove_weather_id_alter_weather_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='weather',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory_app.weather'),
        ),
    ]
